**Рассолова Маргарита Сергеевна, НММбд-02-22**

1. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом 0.05, а затем объедините оба массива чисел как строки в один массив.

In [1]:
import numpy as np

In [2]:
x_values = np.arange(0, 1.05, 0.05)

In [3]:
cos_values = np.cos(x_values)
sin_values = np.sin(x_values)

In [4]:
array = np.column_stack((cos_values, sin_values))

In [5]:
print(array)

[[1.         0.        ]
 [0.99875026 0.04997917]
 [0.99500417 0.09983342]
 [0.98877108 0.14943813]
 [0.98006658 0.19866933]
 [0.96891242 0.24740396]
 [0.95533649 0.29552021]
 [0.93937271 0.34289781]
 [0.92106099 0.38941834]
 [0.9004471  0.43496553]
 [0.87758256 0.47942554]
 [0.85252452 0.52268723]
 [0.82533561 0.56464247]
 [0.7960838  0.60518641]
 [0.76484219 0.64421769]
 [0.73168887 0.68163876]
 [0.69670671 0.71735609]
 [0.65998315 0.75128041]
 [0.62160997 0.78332691]
 [0.58168309 0.8134155 ]
 [0.54030231 0.84147098]]


2. Создайте случайный массив 3×5 с помощью функции np.random.rand(3, 5) и вычислите: сумму всех элементов, сумму строк и сумму столбцов. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)

In [6]:
import numpy as np

In [7]:
random_array = np.random.rand(3, 5)

In [8]:
total_sum = np.sum(random_array) # сумма всех элементов

In [9]:
# Сумма строк и столбцов

row_sums = np.sum(random_array, axis=1)
column_sums = np.sum(random_array, axis=0)

In [10]:
print("Случайный массив:")
print(random_array)
print("\nСумма всех элементов:", total_sum)
print("Суммы по строкам:", row_sums)
print("Суммы по столбцам:", column_sums)

Случайный массив:
[[0.89829974 0.43047171 0.0844071  0.70669686 0.50007142]
 [0.59471089 0.8296476  0.55265497 0.57444965 0.6626554 ]
 [0.54909645 0.99944634 0.28822105 0.55912986 0.17931194]]

Сумма всех элементов: 8.409270964304227
Суммы по строкам: [2.61994682 3.21411851 2.57520564]
Суммы по столбцам: [2.04210708 2.25956565 0.92528312 1.84027636 1.34203875]


3. Создайте случайный массив 5×5, используя функцию np.random.rand(5, 5). Отсортируйте строки по второму столбцу. Используйте для этого slicing + argsort + indexing.

In [11]:
import numpy as np

In [12]:
random_array = np.random.rand(5, 5)

In [13]:
sorted_indices = np.argsort(random_array[:, 1])
sorted_array = random_array[sorted_indices]

In [14]:
print("\nОтсортированный массив по второму столбцу:")
print(sorted_array)


Отсортированный массив по второму столбцу:
[[0.49796526 0.21462668 0.32489338 0.80169601 0.78022247]
 [0.47566426 0.29087583 0.37090132 0.77298711 0.91229439]
 [0.35592146 0.48775551 0.17570487 0.27065123 0.23458433]
 [0.00226744 0.86449587 0.5784104  0.99689559 0.00147814]
 [0.80637791 0.99042043 0.88827174 0.62811648 0.57712037]]


4. Посчитайте две матрицы: B=A^T*A и C=A*A^T. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие? Найдите сумму диагональных элементов матриц B и C. Посчитайте детерминант и ранг матриц A, B и C, посмотрите на спектр (набор собственных значений) матриц B и C, какие выводы вы можете сделать? (подсказка: используйте готовые функции из библиотеки np.linalg).

In [23]:
import numpy as np

In [24]:
A = np.random.rand(3, 4)

In [25]:
B = np.dot(A.T, A) # B = A^T * A

In [26]:
C = np.dot(A, A.T) # C = A * A^T

In [27]:
print("Матрица B:")
print(B)
print("\nМатрица C:")
print(C)

Матрица B:
[[0.55775715 0.20554374 0.11882124 0.71576481]
 [0.20554374 0.97768812 0.31946136 0.47651891]
 [0.11882124 0.31946136 0.11811211 0.20862671]
 [0.71576481 0.47651891 0.20862671 0.9779496 ]]

Матрица C:
[[0.6499763  0.59977169 0.13298043]
 [0.59977169 0.87837174 0.69072112]
 [0.13298043 0.69072112 1.10315894]]


In [28]:
# Сумма диагональных элементов матриц B и C
sum_diagonal_B = np.trace(B)
sum_diagonal_C = np.trace(C)

In [29]:
print("\nСумма диагональных элементов матрицы B:", sum_diagonal_B)
print("Сумма диагональных элементов матрицы C:", sum_diagonal_C)



Сумма диагональных элементов матрицы B: 2.6315069751942044
Сумма диагональных элементов матрицы C: 2.6315069751942044


Находим детерминант и ранг матриц B и C

In [33]:
det_B = np.linalg.det(B)
rang_B = np.linalg.matrix_rank(B)

det_C = np.linalg.det(C)
rang_C = np.linalg.matrix_rank(C)


In [34]:
print("\nДетерминант и ранг матрицы B:", det_B, rank_B)
print("Детерминант и ранг матрицы C:", det_C, rank_C)



Детерминант и ранг матрицы B: 0.0 3
Детерминант и ранг матрицы C: 0.017528464933907608 3


In [35]:
# Спектр (собственные значения) матриц B и C
eigenvalues_B = np.linalg.eigvals(B)
eigenvalues_C = np.linalg.eigvals(C)

In [36]:
print("\nСпектр матрицы B (собственные значения):", eigenvalues_B)
print("Спектр матрицы C (собственные значения):", eigenvalues_C)


Спектр матрицы B (собственные значения): [ 1.89714883e+00  7.21553310e-01 -8.30439142e-18  1.28048371e-02]
Спектр матрицы C (собственные значения): [1.89714883 0.72155331 0.01280484]
